# config.yml

data:
  image_size: 32
  mean: [0.4914, 0.4822, 0.4465]
  std: [0.247, 0.243, 0.261]
  random_rotation: 20
  random_horizontal_flip: 0.1
  color_jitter:
    brightness: 0.1
    contrast: 0.1
    saturation: 0.1
  random_sharpness:
    factor: 2
    p: 0.1
  random_erasing:
    probability: 0.75
    scale: [0.02, 0.1]
    value: 1.0
    inplace: True
training:
  epochs: 2
  batch_size: 100
  learning_rate: 0.1
  momentum: 0.2
  model:
    out_conv_1: 32
    out_conv_2: 64
    out_conv_3: 128
    dropout_p: 0.5
