name: Run unit tests

on:
    pull_request:
        branches:
            - main
            - develop
    push:
        branches:
            - main
            - develop

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Check out the repository
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: 3.10

            - name: Install dependencies
              run: |
                pip install --upgrade pip poetry==1.8.3
                poetry install

            - name: Run data tests
              run: pytest -v -s --disable-warnings --cov=src/cifar_classifier/data --cov-report=xml:c --cov-fail-under=90 tests

            - name: Upload Coverage Report
              uses: actions/upload-artifact@v3
              with:
                name: coverage-report
                path: reports/coverage.xml
