name: Run unit tests

on:
    pull_request:
        branches:
            - main
            - release
            - develop

jobs:
    test:
        # runs-on: pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel
        runs-on: python:3.10-bullseye

        if: github.ref == 'refs/heads/develop'
        steps:
            - uses: ./.github/workflows/reusable_setup.yml

            - name: Run data tests
              run: |
                make tests

            - name: Upload Coverage Report
              uses: actions/upload-artifact@v3
              with:
                name: coverage-report
                path: reports/coverage.xml
    train:
        # runs-on: pytorch/pytorch:2.4.0-cuda12.4-cudnn9-devel
        runs-on: python:3.10-bullseye

        if: github.ref == 'refs/heads/release' || contains(github.event.commits.*.modified, 'src/cifar_classifier/model/train_model.py')

        steps:
            - uses: ./.github/workflows/reusable_setup.yml

            - name: Train model
              # if:
              #   changes:
              #       - 'src/cifar_classifier/model/train_model.py'
              run: |
                python3 src/cifar_classifier/model/train_model.py --experiment_name staging_cifar_classifier --team MLOps --run-reason challenger

            - name: Challenger model evaluation
              # if:
              #   changes:
              #       - 'src/cifar_classifier/model/train_model.py'
              run: |
                pass

            - name: Docker build
              # if:
              #   changes:
              #       - 'Dockerfile'
              run: |
                pass

            - name: Integration tests
              # if:
              #   changes:
              #       - 'src/cifar_classifier/model/train_model.py'
              run: |
                pass
